### ISSUE TITLE
gateway not running

### ISSUE THREAD

**Issue by ztsyed** [peterrosell/ceph-coreos-vagrant#1]
Ceph cluster is up. 

root@1f0ae637c5f2:/app# ceph -w
    cluster a011a24e-666e-48c4-a382-ad92b90c5e9f
     health HEALTH_OK
     monmap e1: 1 mons at {core-01=172.21.13.101:6789/0}, election epoch 2, quorum 0 core-01
     osdmap e20: 3 osds: 3 up, 3 in
      pgmap v30: 832 pgs, 7 pools, 1158 bytes data, 13 objects
            15437 MB used, 14788 MB / 36396 MB avail
                 832 active+clean

But when trying to run the gateway container, i am getting the following error

core@core-01 ~ $ /usr/bin/docker run --rm --name ceph-gateway --net host --env HOST=172.21.13.101 --env EXTERNAL_PORT=8888 -p 8888:8888 erix.net:5000/ceph-gateway
Starting Gateway Boot
Gateway Boot: 172.21.13.101:4001
Gateway generating key
Gateway setting etcd alternative
Gateway generating admin user
Starting RADOS gateway...
/usr/bin/radosgw is not running.

**Comment by peterrosell** [comment]
I haven't been working on this project for a while due to problem with getting several OSDs running on the same host. During my pause Ceph has started to do some docker containers in their project ceph/ceph-docker. I have tried to use that base to solve my problem and we finally found the cause of the problem, the OSDs are doing some process searching when running on same host and when they use --net=host they also need --pid=host. Details here, https://github.com/ceph/ceph-docker/issues/19. 
Lately I have continued getting Ceph up and running with the S3 interface and just found out the reason radosgw doesn't start is that no ceph pools are created. I have taken a lot of inspiration and code from the deis project and their store modules. Here are a docker container that I haven't included in my setup yet. https://github.com/deis/deis/blob/master/store/metadata/bin/boot . As you can see a couple of pools are created there. I guess it will help adding that to the setup. I will do it when I get some free time.

**Comment by peterrosell** [comment]
I pushed my last changes and I managed to get the gateway running too. It hasn't been tested a lot, just one time so there might be some problems. I have seen problems when I have several OSDs on the same host and hibernates my laptop and then starts it again. The OSDs goes crazy and I have to destroy the cluster and recreate it from scratch. I hope to solve that in awhile.

**Comment by ztsyed** [comment]
Thanks a lot. It works now. I am able to connect to s3 interface using DragonDisk. Not able to create buckets but I assume I need to follow the steps here http://docs.ceph.com/docs/master/radosgw/config/#enabling-subdomain-s3-calls

**Comment by peterrosell** [comment]
I have written a description of how to do this setup in another repository, https://github.com/peterrosell/multinode-ceph-vagrant. If you like you can read some info there and see if you can get it to work. With that setup I have been able to create a bucket and upload/download files.
